batch_size: 256
channels: 32,64,64,128,128
dec_type: both
drop_rate: 0.0
early_stop_patience: 2500
enc_type: cnn
epsilon_std: 0.01
fc_dim: 512
k_sizes: 1,3,3,5,5
kld_full_value: 0.5
kld_wt_one_at_epoch: 2000
kld_wt_zero_for_epochs: 1000
kld_zero_value: 1.0e-15
lambda_diag: 10.0
lambda_offdiag: 5.0
latent_size: 256
layer_symbol: LAY
length_encoding: true
lr_ini: 0.0001
lr_min: 1.0e-06
lr_reduce_factor: 0.2
lr_reduce_patience: 1500
max_depth: 10
max_len: 56
max_steps: 10
n_chars: 29
num_projections: 50
num_workers: 7
p: 2.0
regweight: 100
rnn_hidden: 512
rnn_layers: 3
strides: 1,2,1,2,1
temperature: -0.1
weighted_sampling: true
weights_path: null
